(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "expand-region")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "multiple-cursors")
(depends-on "popwin")
(depends-on "use-package")
(depends-on "markdown-mode")
(depends-on "zotxt")

