#!/usr/bin/env zsh
#
# Copyright (C) 2015-2017 Dyne.org Foundation
#
# Designed, written and maintained by Denis Roio <jaromil@dyne.org>
#
# This source code is free software; you can redistribute it
# and/or modify it under the terms of the GNU Public License
# as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later
# version.
#
# This source code is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.  Please refer to the GNU Public License for more
# details.
#
# You should have received a copy of the GNU Public License
# along with this source code; if not, write to: Free
# Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
# 02139, USA.

# full path to writedown's system
[[ -r /usr/local/writedown ]] && R=/usr/local/writedown
[[ -d writedown ]] && R=`pwd`/writedown

mkdir -p pub
mkdir -p views

[[ -r config.zsh ]] || cp $R/config.zsh .

[[ -r views/index.txt ]] ||
    cat <<EOF > views/index.txt
first_chapter.md
second_chapter.md
third_chapter.md
EOF

[[ -r views/template.tex ]] || cp $R/template.tex views/template.tex

[[ -r views/references.bib ]] ||
    cat <<EOF > views/references.bib
@article{Bianchi_2011,
  author       = {Bianchi, Amos and Roio, Denis Jaromil},
  title        = {Frames from the Life and Death of Jean Charles de Menezes},
  year         = 2011,
  pages        = {101-109},
  isbn         = {http://id.crossref.org/isbn/978-94-007-0641-5},
  journal      = {Computers, Privacy and Data Protection: an Element of Choice},
  publisher    = {Springer}
}

@article{roio2013bitcoin_jaromil,
  title={Bitcoin, the end of the Taboo on Money},
  author={Roio, Denis Jaromil},
  journal={Media-N: ISEA2012 Machine Wilderness},
  pages={40},
  year={2013},
  publisher={ISEA}
}

@article{roio2012re,
  title={Re/think Re/design},
  author={Roio, Denis Jaromil},
  journal={Technoetic Arts},
  volume={9},
  number={2-3},
  pages={197-208},
  year={2012},
  publisher={Intellect}
}

@article{dowse_whitepaper,
  title={Dowse Whitepaper, v1.2},
  year={2015},
  author={Roio, Denis Jaromil},
  publisher={Dyne.org digital press}
}
EOF

[[ -r views/abstract.txt ]] ||
    cat <<EOF > views/abstract.txt
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
EOF

[[ -r views/first_chapter.md ]] ||
    cat <<EOF > views/first_chapter.md
# de Finibus Bonorum et Malorum

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat [@Bianchi_2011]. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
EOF

[[ -r views/second_chapter.md ]] ||
    cat <<EOF > views/second_chapter.md
# Voluptas

Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo [@dowse_whitepaper]. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt [@roio2013bitcoin_jaromil]. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
EOF

[[ -r views/third_chapter.md ]] ||
    cat <<EOF > views/third_chapter.md
# Tempora

At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio [@roio2012re]. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.
EOF
